$('.hero_area_slider_box').owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})

$('.latest_post_slider').owlCarousel({
    loop:true,
    margin:0,
    nav:false,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        800:{
            items:2
        },
        1000:{
            items:3
        },1200:{
            items:4
        }
    }
})